In [16]:
import numpy as np

import torch

import rdkit.Chem as Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole

from MolJuncTree import MolJuncTree

from nnutils import index_select_ND 


In [30]:
x = []
x.append([0] * 6)

In [31]:
x

[[0, 0, 0, 0, 0, 0]]

In [17]:
source = torch.randn(5,4)

In [18]:
source

tensor([[ 0.6980, -1.1377,  0.4562,  0.9241],
        [ 0.1853, -1.1339, -0.9788,  0.3148],
        [ 0.0570,  0.8324, -0.2971,  0.5712],
        [-0.8752, -0.1708, -0.8148,  2.1042],
        [-0.9011,  0.2681, -0.0036,  0.3677]])

In [19]:
index = [torch.LongTensor(np.random.choice(5, 2)) for idx in range(5)]

In [20]:
index = torch.stack(index, dim=0)

In [21]:
index

tensor([[1, 1],
        [1, 1],
        [0, 0],
        [4, 4],
        [2, 1]])

In [27]:
x = torch.index_select(source, 0, index[:, 0])
y = torch.index_select(source, 0, index[:, 1])

In [28]:
x

tensor([[ 0.1853, -1.1339, -0.9788,  0.3148],
        [ 0.1853, -1.1339, -0.9788,  0.3148],
        [ 0.6980, -1.1377,  0.4562,  0.9241],
        [-0.9011,  0.2681, -0.0036,  0.3677],
        [ 0.0570,  0.8324, -0.2971,  0.5712]])

In [29]:
y

tensor([[ 0.1853, -1.1339, -0.9788,  0.3148],
        [ 0.1853, -1.1339, -0.9788,  0.3148],
        [ 0.6980, -1.1377,  0.4562,  0.9241],
        [-0.9011,  0.2681, -0.0036,  0.3677],
        [ 0.1853, -1.1339, -0.9788,  0.3148]])